BookStore/Models/Book.cs
namespace Bookstore.Models;

public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public int PageCount { get; set; }
    public string Isbn { get; set; }
}

BookStore/Models/ErrorViewModel.cs
namespace Bookstore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BookStore/Controllers/BookstoreController.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Controllers;

public class BookstoreController : Controller
{
    private static IList<Book> books = new List<Book>
    {
        new Book
        {
            Id = 1,
            Title = "Wiedźmin. Miecz przeznaczenia",
            Author = "A.Sapkowski",
            PageCount = 400,
            Isbn = "9788090091252"
        },
        new Book
        {
            Id = 2,
            Title = "Wiedźmin. Ostatnie życzenie",
            Author = "A. Sapkowski",
            PageCount = 332,
            Isbn = "9788078282821"
        },
        new Book
        {
            Id = 3,
            Title = "How to train your dragon",
            Author = "Cowell Cressid",
            PageCount = 214,
            Isbn = "985-0-672-91810-3"
        },
        new Book
        {
            Id = 4,
            Title = "Władca pierścieni. Drużyna pierścienia",
            Author = "J.R.R. Tolkien",
            PageCount = 426,
            Isbn = "978-0-395-19395-7"
        },
        new Book
        {
            Id = 5,
            Title = "Hobbit, czyli tam i z powrotem",
            Author = "J.R.R Tolkien",
            PageCount = 320,
            Isbn = "978-1-85326-120-9"
        }
    };

    private readonly ILogger<BookstoreController> _logger;

    public BookstoreController(ILogger<BookstoreController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View(books);
    }

    // GET: FilmController/Details/5
    public ActionResult Details(int id)
    {
        return View(books.FirstOrDefault(book => book.Id == id));
    }

    // GET: FilmController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: FilmController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Book book)
    {

        book.Id = books.Count + 1;
        books.Add(book);
        return RedirectToAction("Index");
    }

    // GET: FilmController/Edit/5
    public ActionResult Edit(int id)
    {
        return View(books.FirstOrDefault(book => book.Id == id));
    }

    // POST: FilmController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, Book book)
    {
        Book bookToEdit = books.FirstOrDefault(book => book.Id == id);

        bookToEdit.Title = book.Title;
        bookToEdit.Author = book.Author;
        bookToEdit.Isbn = book.Isbn;

        return RedirectToAction("Index");
    }

    // GET: FilmController/Delete/5
    public ActionResult Delete(int id)
    {
        return View(books.FirstOrDefault(book => book.Id == id));
    }

    // POST: FilmController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(Book book, int id)
    {
        Book bookToRemove = books.FirstOrDefault(x => x.Id == id);
        books.Remove(bookToRemove);
        return RedirectToAction("Index");
    }


}

BookStore/Controllers/HomeController.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookstore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BookStore/Views/Bookstore/Create.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PageCount" class="control-label"></label>
                <input asp-for="PageCount" class="form-control" />
                <span asp-validation-for="PageCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookStore/Views/Bookstore/Delete.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStore/Views/Bookstore/Details.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PageCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PageCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

BookStore/Views/Bookstore/Edit.cshtml
@model Bookstore.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookStore/Views/Bookstore/Index.cshtml
@model IEnumerable<Bookstore.Models.Book>

@{
    ViewData["Title"] = "Bookshelf";
}

<h1>Manage your books</h1>

<p>
    <a asp-action="Create">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new {  id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

BookStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Bookstore</h1>
    <p>
        This application allows you to easily manage and track your book inventory.
    </p>

    <p>
        Whether you're a bookstore owner or just a book enthusiast, our platform simplifies the process of adding, editing, and removing books from your collection. Enjoy efficient CRUD (Create, Read, Update, Delete) operations on your book catalog.
    </p>

    <p>
        Feel free to explore the application and start managing your books today!
    </p>
</div>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookstore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookstore" asp-action="Index">Bookstore Management Panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bookstore MB
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>